-- Catalog item photos use Supabase Storage when ITEM_IMAGES_STORAGE=supabase (default).
--
-- 1. Dashboard → Storage → New bucket
--    Name: item-images
--    Public bucket: ON  (catalog and detail pages load images by public URL)
--
-- 2. The API uploads with the service role key (server-side). No anon upload policy is required
--    unless you add a direct browser upload later.
--
-- 3. Optional: add a policy so authenticated admins can manage objects from the dashboard only;
--    public read is satisfied by marking the bucket public.
